### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by szsomlai** [iamrasel/lunar-launcher#12]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

What is the method to leave the ToDo page?

### Additional information

After reaching it with longpress on homescreen, I get the ToDo page and it is stuck on top of everything. I can see the homepage, I can even interact with it (swipe) on the edge margins, but no option to leave ToDo overlay.

**Comment by iamrasel** [comment]
This issue is already solved. Try the latest version from github release or wait for the next f-droid build.

**Comment by szsomlai** [comment]
Greetings! Today I have downloaded the launcher from github, but the ToDo overlay still sticks on the screen. The 'back', and the 'home' button does nothing.Sent from my phone-------- Original message --------From: Md Rasel Hossain ***@***.***>Date: Thu, Sep 22, 2022, 08:57To: iamrasel/lunar-launcher ***@***.***>Cc: szsomlai ***@***.***>, Author ***@***.***>Subject: Re: [iamrasel/lunar-launcher] ToDo (Issue #12)
This issue is already solved. Try the latest version from github release or wait for the next f-droid build.

**Comment by iamrasel** [comment]
@szsomlai are you sure that you've tried the latest version?
