### ISSUE TITLE
TODO editing shows on top of the other screens

### ISSUE THREAD

**Issue by migueldeoleiros** [iamrasel/lunar-launcher#129]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.8.2 (38)

### Android version

EMUI 12 (Android 11 [not sure])

### Steps to reproduce the bug

1. Open todo editing
2. Swipe from the edge

### Expected behavior

You shoudn't see the todo editing on any other screen other than the main one, or you shoudn't be able to move to the other screens while editing

### Screenshots/Screen recordings

https://github.com/iamrasel/lunar-launcher/assets/63507487/5f27aec7-646b-4fc1-a134-cfe6891e2f12

### Additional information

In the video I show the pop up on top the RSS feed, but it also does the same on top of the app list and of top of the system info.
I think it would be ideal to disable the swipe gestures to move screens when editing the todos.
I suspect this behavior is causing issue #45 which I also experience
