### ISSUE TITLE
[Feature Request] Reminder of ToDo

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#33]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

It would be useful to have the ability to add a reminder to some date or time for the ToDo's.

**Comment by iamrasel** [comment]
Will do someday.
