### ISSUE TITLE
Move "add Todo Window" higher

### ISSUE THREAD

**Issue by erdnuesse** [iamrasel/lunar-launcher#43]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Didn't know if bug or feature, so feature first, move, if bug.

When I add a Todo, the text field and two buttons are visible.
When the keyboard opens, I can see what I typed. So far, so good. 
But when I finished the entry, I need to close the keyboard to see the save \ cancel buttons again, which should be unnecessary, especially with that much screen real estate. 

for quick additions of multiple entries, it really disturbs the workflow, closing and opening the keyboard each time. 

expected: 
move everything higher, so I can add each entry without closing the keyboard. 

screenshot;
![Screenshot_20230112-225204](https://user-images.githubusercontent.com/4510296/212190128-b70cda9e-4e96-457f-883e-3420b805d691.png)
