### ISSUE TITLE
[Bug report and feature req.] To-do list locking user if he uses gesture navigations

### ISSUE THREAD

**Issue by Glesas** [iamrasel/lunar-launcher#45]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.2.2

### Android version

Android 10, Emui 12

### Steps to reproduce the bug

1. Go to main screen of launcher (desktop)
2. Hold tap to open To-do list
3. Done

### Expected behavior

I'm expected to be able to hold tap same way before, to get out off to-do list, or atleast by using gesture navigation, to be able make gesture of "back" button.
But I can't do it,  when I trying to make "go back" (close) gesture, it would let me only open quick access of apps (built in feature of phone). So I can't leave from To-do list at all, if I'm using gesture navigation. With default 3 buttons, the back buttons works properly (left one). 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/43447667/212941811-03c1e8b7-25a0-43a4-bd30-d58d922d77b0.mp4

### Additional information

Please add ability to close to do list, the same way, as you open it. Or gesture navigation unblocking, so it would be possible to use back button of gestures.

**Comment by iamrasel** [comment]
Hello @Glesas, I couldn't understand your issue properly. If you can get back from todo list using android's native navigation (button/gesture), then everything is working perfectly.

But I think you are trying to use the left-right swipe function to return to home screen, but those gestures are only available in the main window (feeds⟷home⟷app drawer). When you enter the todo manager long pressing on home screen, you just replace the main window with todo manager's window. So, those gestures become unavailable there.

**Comment by Glesas** [comment]
Oh, i see how to-do list is working. I just noticed, that gesture of back button is not avaliable on any of those main screens (feeds⟷home⟷app drawer).  And i've not just seamlessly swiped from left to right screen. I've properly tried to make back gesture (could be seen on video), but it was at any cost, at "being quick access" state.
I'll try to rephrase main question: 
Can android gesture navigation be somehow overwritten to a specific app? (Say for example "Gesture back" always must be "back" button, and not become quick-access menu at any cost) 
Because "back" gesture, does not working on any of main screens (even with keyboard on).
Not working as intended gesture, can make user stuck inside of to-do list, with no way of escaping it, besides changing navigation style.
I'm sorry for my lack of knowledge of English language, but i tried to explain as best as i could the issue

**Comment by migueldeoleiros** [comment]
> If you can get back from todo list using android's native navigation (button/gesture), then everything is working perfectly.

I also have the same problem, using a a Huawei Nova 5T, it seems that @Glesas is also using a Huawei. I suspect EMUI has a different implementation of the navigation gestures.
The problem is that when you enter the todo list editing mode you can't exit using gesture navigation. The "go back" gesture is swiping from the sides.

**Comment by migueldeoleiros** [comment]
As I mentioned in issue #129 I think the swipe gestures from the app could be in conflict with the OS ones, and that's what locks you in.

**Comment by fs-sifat** [comment]
> As I mentioned in issue #129 I think the swipe gestures from the app could be in conflict with the OS ones, and that's what locks you in.

Doubt that. Usually critical task like gesture navigation have a higher priority to receive an event to process. It's more likely that the app isn't handling the swipe back event.
