### ISSUE TITLE
Switching to app list even when to-do list is on

### ISSUE THREAD

**Issue by salihburock** [iamrasel/lunar-launcher#96]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.8

### Android version

Android 12-13

### Steps to reproduce the bug

1. Hold the background to trigger to-do list menu.
2. Keep holding after to-do menu shows up
3. Swipe to app list without raising your finger
4. To-do list is still on in app list menu

### Expected behavior

After to-do list is opened hold action should be revoked at app-side otherwise the action is not prevented 

### Screenshots/Screen recordings

https://github.com/iamrasel/lunar-launcher/assets/94194901/e86e6069-fd5a-41ec-90c8-045301718220

### Additional information

I realized that accidently on a A12 device. Tried on A13 and saw the same result. I don't think it would happen on daily use but still wanted to report.
